// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ5qwlK9PM2x_XutjZOeRTmujOvRYKZjY',
    appId: '1:470678893379:web:15500ceb39de830e68b5f6',
    messagingSenderId: '470678893379',
    projectId: 'instantchatapp-aa2fb',
    authDomain: 'instantchatapp-aa2fb.firebaseapp.com',
    storageBucket: 'instantchatapp-aa2fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ5qwlK9PM2x_XutjZOeRTmujOvRYKZjY',
    appId: '1:470678893379:android:15500ceb39de830e68b5f6',
    messagingSenderId: '470678893379',
    projectId: 'instantchatapp-aa2fb',
    storageBucket: 'instantchatapp-aa2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ5qwlK9PM2x_XutjZOeRTmujOvRYKZjY',
    appId: '1:470678893379:ios:15500ceb39de830e68b5f6',
    messagingSenderId: '470678893379',
    projectId: 'instantchatapp-aa2fb',
    storageBucket: 'instantchatapp-aa2fb.firebasestorage.app',
    iosBundleId: 'com.example.instant_chat_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ5qwlK9PM2x_XutjZOeRTmujOvRYKZjY',
    appId: '1:470678893379:ios:15500ceb39de830e68b5f6',
    messagingSenderId: '470678893379',
    projectId: 'instantchatapp-aa2fb',
    storageBucket: 'instantchatapp-aa2fb.firebasestorage.app',
    iosBundleId: 'com.example.instant_chat_app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ5qwlK9PM2x_XutjZOeRTmujOvRYKZjY',
    appId: '1:470678893379:web:15500ceb39de830e68b5f6',
    messagingSenderId: '470678893379',
    projectId: 'instantchatapp-aa2fb',
    authDomain: 'instantchatapp-aa2fb.firebaseapp.com',
    storageBucket: 'instantchatapp-aa2fb.firebasestorage.app',
  );
}
